# Generated by Django 5.1.1 on 2024-10-09 18:16

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos', validators=[Petstagram.photos.validators.MaxFileSizeValidator(5)]),
        ),
    ]
